# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.decision_log_response import DecisionLogResponse
from .raw_client import AsyncRawDecisionsClient, RawDecisionsClient
from .types.query_decisions_request_count import QueryDecisionsRequestCount
from .types.query_decisions_request_include_traces import QueryDecisionsRequestIncludeTraces
from .types.query_decisions_request_order import QueryDecisionsRequestOrder
from .types.query_decisions_request_sort import QueryDecisionsRequestSort


class DecisionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDecisionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDecisionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDecisionsClient
        """
        return self._raw_client

    def query(
        self,
        *,
        search: typing.Optional[str] = None,
        rules: typing.Optional[str] = None,
        flows: typing.Optional[str] = None,
        contexts: typing.Optional[str] = None,
        trace: typing.Optional[str] = None,
        statuses: typing.Optional[str] = None,
        include_traces: typing.Optional[QueryDecisionsRequestIncludeTraces] = None,
        item_filter: typing.Optional[str] = None,
        start: typing.Optional[dt.datetime] = None,
        end: typing.Optional[dt.datetime] = None,
        sort: typing.Optional[QueryDecisionsRequestSort] = None,
        order: typing.Optional[QueryDecisionsRequestOrder] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        count: typing.Optional[QueryDecisionsRequestCount] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DecisionLogResponse:
        """
        Query decision logs with support for the decision data query language, rule/status filters, date ranges, and pagination. The query language supports field comparisons (e.g., `alpha=0`, `score>10`), contains/not-contains (e.g., `name:John`, `status!:error`), boolean logic (`AND`, `OR`), and parentheses for grouping.

        Parameters
        ----------
        search : typing.Optional[str]
            Decision data query language expression to filter logs by request/response data. Supports field comparisons (`field=value`, `field>10`), contains (`field:text`), not-contains (`field!:text`), boolean operators (`AND`, `OR`), and parentheses. A bare UUID or 32-hex term resolves as an execution/correlation-id lookup automatically.

        rules : typing.Optional[str]
            Comma-separated list of rule names, IDs, or slugs to filter logs by. Names match partially; IDs and slugs match exactly.

        flows : typing.Optional[str]
            Comma-separated list of flow names, IDs, or slugs to filter logs by. Matches only flow-level execution logs; the rule executions that ran inside a flow are separate records and are not included.

        contexts : typing.Optional[str]
            Comma-separated list of context names or slugs to filter logs by. Matches the rule and flow executions that were triggered by those contexts (batch and interactive updates).

        trace : typing.Optional[str]
            Execution-trace correlation id. Returns every decision log from one execution tree: pass a log's `decision.root_flow_execution_id` (or any `flow_execution_id` / `parallel_execution_id`, including a bulk run's per-item `item_execution_ids` entries) to retrieve the flow-level record plus all subflow and rule records from that run. On self-hosted deployments, a log's observability `trace_id` is also accepted. Combine with `rules` or `search` to narrow to a specific rule or payload within the run.

        statuses : typing.Optional[str]
            Comma-separated list of HTTP status codes to filter logs by.

        include_traces : typing.Optional[QueryDecisionsRequestIncludeTraces]
            When `true`, each flow record in the response includes a decompressed `path_trace` field: the run's executed steps with their full inputs and outputs (an object for single runs, a null-aligned array matching the request array for bulk runs). Off by default - traces are stored compressed and can be large, so only enable this when you need them. Ignored in count mode.

        item_filter : typing.Optional[str]
            Bulk payload filter in the form `path=value`. For each bulk record in the results (array-shaped request/response), keeps only the items whose payload value at `path` equals `value`, slicing the `request` and `response` arrays and every index-aligned field (`decision.item_execution_ids`, `decision.item_indexes`, `decision.success_idxs`, and `path_trace` when `include_traces=true`) in lockstep so input/output alignment is preserved. Filtered records gain a `matched_items` array with the surviving items' original zero-based positions. Paths use dot notation into each item (`customer.id`, `lines.0.sku`); prefix with `request.` or `response.` to match only that side (unprefixed paths match either side). Values compare as exact scalar strings (`status=200`, `approved=true`). Non-bulk records are returned unchanged; bulk records with no matching items are returned with empty item arrays. Typical use: combine with `search`, `flows`, or `trace` to locate a bulk run, then isolate one item's payloads and its `item_execution_ids` entry without tracking indexes. Ignored in count mode.

        start : typing.Optional[dt.datetime]
            Start date for the query range (ISO8601 format). Hosted queries may span at most 90 days. Persistent self-hosted queries may use any range within local ClickHouse retention; PVC-less archive mode is limited to 7 days. Defaults to the applicable maximum before `end` (or before now).

        end : typing.Optional[dt.datetime]
            End date for the query range (ISO8601 format). Defaults to now. When supplied without `start`, the query covers the preceding 90 days on hosted/table mode or 7 days in PVC-less archive mode.

        sort : typing.Optional[QueryDecisionsRequestSort]
            Column to sort results by. `time` orders by execution timestamp, `name` by rule/flow name, `status` by HTTP status code, and `type` by operation (solve, bulk-solve, flows, etc.). Defaults to `time`.

        order : typing.Optional[QueryDecisionsRequestOrder]
            Sort direction. Defaults to `desc`.

        cursor : typing.Optional[str]
            Opaque pagination token returned by the previous response. Pass it back verbatim to fetch the next page; do not construct or modify cursor values.

        limit : typing.Optional[int]
            Number of results to return per page (default: 100, maximum: 1000). Logs carry full request/response payloads, so use smaller limits when querying workspaces with large bulk operations. Time-sorted pagination uses a keyset cursor, so its scan cost does not grow with page depth.

        count : typing.Optional[QueryDecisionsRequestCount]
            If set to 'true', returns only the count of matching logs instead of the log data.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DecisionLogResponse
            Successful response

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.decisions.query(
            search="status=200",
            rules="Lead Qualification,Pricing Calculator",
            flows="Loan Approval Flow",
            contexts="loans",
            trace="7db50259-31a0-42c1-aa3c-36409ad3c756",
            statuses="200,400,500",
            item_filter="customer.id=cst_8f3a12",
        )
        """
        _response = self._raw_client.query(
            search=search,
            rules=rules,
            flows=flows,
            contexts=contexts,
            trace=trace,
            statuses=statuses,
            include_traces=include_traces,
            item_filter=item_filter,
            start=start,
            end=end,
            sort=sort,
            order=order,
            cursor=cursor,
            limit=limit,
            count=count,
            request_options=request_options,
        )
        return _response.data


class AsyncDecisionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDecisionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDecisionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDecisionsClient
        """
        return self._raw_client

    async def query(
        self,
        *,
        search: typing.Optional[str] = None,
        rules: typing.Optional[str] = None,
        flows: typing.Optional[str] = None,
        contexts: typing.Optional[str] = None,
        trace: typing.Optional[str] = None,
        statuses: typing.Optional[str] = None,
        include_traces: typing.Optional[QueryDecisionsRequestIncludeTraces] = None,
        item_filter: typing.Optional[str] = None,
        start: typing.Optional[dt.datetime] = None,
        end: typing.Optional[dt.datetime] = None,
        sort: typing.Optional[QueryDecisionsRequestSort] = None,
        order: typing.Optional[QueryDecisionsRequestOrder] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        count: typing.Optional[QueryDecisionsRequestCount] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DecisionLogResponse:
        """
        Query decision logs with support for the decision data query language, rule/status filters, date ranges, and pagination. The query language supports field comparisons (e.g., `alpha=0`, `score>10`), contains/not-contains (e.g., `name:John`, `status!:error`), boolean logic (`AND`, `OR`), and parentheses for grouping.

        Parameters
        ----------
        search : typing.Optional[str]
            Decision data query language expression to filter logs by request/response data. Supports field comparisons (`field=value`, `field>10`), contains (`field:text`), not-contains (`field!:text`), boolean operators (`AND`, `OR`), and parentheses. A bare UUID or 32-hex term resolves as an execution/correlation-id lookup automatically.

        rules : typing.Optional[str]
            Comma-separated list of rule names, IDs, or slugs to filter logs by. Names match partially; IDs and slugs match exactly.

        flows : typing.Optional[str]
            Comma-separated list of flow names, IDs, or slugs to filter logs by. Matches only flow-level execution logs; the rule executions that ran inside a flow are separate records and are not included.

        contexts : typing.Optional[str]
            Comma-separated list of context names or slugs to filter logs by. Matches the rule and flow executions that were triggered by those contexts (batch and interactive updates).

        trace : typing.Optional[str]
            Execution-trace correlation id. Returns every decision log from one execution tree: pass a log's `decision.root_flow_execution_id` (or any `flow_execution_id` / `parallel_execution_id`, including a bulk run's per-item `item_execution_ids` entries) to retrieve the flow-level record plus all subflow and rule records from that run. On self-hosted deployments, a log's observability `trace_id` is also accepted. Combine with `rules` or `search` to narrow to a specific rule or payload within the run.

        statuses : typing.Optional[str]
            Comma-separated list of HTTP status codes to filter logs by.

        include_traces : typing.Optional[QueryDecisionsRequestIncludeTraces]
            When `true`, each flow record in the response includes a decompressed `path_trace` field: the run's executed steps with their full inputs and outputs (an object for single runs, a null-aligned array matching the request array for bulk runs). Off by default - traces are stored compressed and can be large, so only enable this when you need them. Ignored in count mode.

        item_filter : typing.Optional[str]
            Bulk payload filter in the form `path=value`. For each bulk record in the results (array-shaped request/response), keeps only the items whose payload value at `path` equals `value`, slicing the `request` and `response` arrays and every index-aligned field (`decision.item_execution_ids`, `decision.item_indexes`, `decision.success_idxs`, and `path_trace` when `include_traces=true`) in lockstep so input/output alignment is preserved. Filtered records gain a `matched_items` array with the surviving items' original zero-based positions. Paths use dot notation into each item (`customer.id`, `lines.0.sku`); prefix with `request.` or `response.` to match only that side (unprefixed paths match either side). Values compare as exact scalar strings (`status=200`, `approved=true`). Non-bulk records are returned unchanged; bulk records with no matching items are returned with empty item arrays. Typical use: combine with `search`, `flows`, or `trace` to locate a bulk run, then isolate one item's payloads and its `item_execution_ids` entry without tracking indexes. Ignored in count mode.

        start : typing.Optional[dt.datetime]
            Start date for the query range (ISO8601 format). Hosted queries may span at most 90 days. Persistent self-hosted queries may use any range within local ClickHouse retention; PVC-less archive mode is limited to 7 days. Defaults to the applicable maximum before `end` (or before now).

        end : typing.Optional[dt.datetime]
            End date for the query range (ISO8601 format). Defaults to now. When supplied without `start`, the query covers the preceding 90 days on hosted/table mode or 7 days in PVC-less archive mode.

        sort : typing.Optional[QueryDecisionsRequestSort]
            Column to sort results by. `time` orders by execution timestamp, `name` by rule/flow name, `status` by HTTP status code, and `type` by operation (solve, bulk-solve, flows, etc.). Defaults to `time`.

        order : typing.Optional[QueryDecisionsRequestOrder]
            Sort direction. Defaults to `desc`.

        cursor : typing.Optional[str]
            Opaque pagination token returned by the previous response. Pass it back verbatim to fetch the next page; do not construct or modify cursor values.

        limit : typing.Optional[int]
            Number of results to return per page (default: 100, maximum: 1000). Logs carry full request/response payloads, so use smaller limits when querying workspaces with large bulk operations. Time-sorted pagination uses a keyset cursor, so its scan cost does not grow with page depth.

        count : typing.Optional[QueryDecisionsRequestCount]
            If set to 'true', returns only the count of matching logs instead of the log data.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DecisionLogResponse
            Successful response

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.decisions.query(
                search="status=200",
                rules="Lead Qualification,Pricing Calculator",
                flows="Loan Approval Flow",
                contexts="loans",
                trace="7db50259-31a0-42c1-aa3c-36409ad3c756",
                statuses="200,400,500",
                item_filter="customer.id=cst_8f3a12",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.query(
            search=search,
            rules=rules,
            flows=flows,
            contexts=contexts,
            trace=trace,
            statuses=statuses,
            include_traces=include_traces,
            item_filter=item_filter,
            start=start,
            end=end,
            sort=sort,
            order=order,
            cursor=cursor,
            limit=limit,
            count=count,
            request_options=request_options,
        )
        return _response.data
