# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..types.bulk_rule_response_item import BulkRuleResponseItem
from ..types.dynamic_request_payload import DynamicRequestPayload
from ..types.dynamic_response_payload import DynamicResponsePayload
from ..types.parallel_solve_request import ParallelSolveRequest
from ..types.parallel_solve_response import ParallelSolveResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawRulesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def solve(
        self, slug: str, *, request: DynamicRequestPayload, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DynamicResponsePayload]:
        """
        Executes a single rule identified by a unique slug. The request and response formats are dynamic, dependent on the rule configuration.

        Parameters
        ----------
        slug : str
            The unique identifier for the resource.

        request : DynamicRequestPayload

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DynamicResponsePayload]
            Rule execution successful. The response structure depends on the rule configuration.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"solve/{jsonable_encoder(slug)}",
            method="POST",
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DynamicResponsePayload,
                    parse_obj_as(
                        type_=DynamicResponsePayload,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def bulk_solve(
        self,
        slug: str,
        *,
        request: typing.Sequence[DynamicRequestPayload],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[BulkRuleResponseItem]]:
        """
        Executes a particular rule against multiple request data payloads provided in a list.

        Parameters
        ----------
        slug : str
            The unique identifier for the resource.

        request : typing.Sequence[DynamicRequestPayload]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[BulkRuleResponseItem]]
            Bulk rule execution successful. The response is an array of results, each dependent on the rule configuration.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"bulk-solve/{jsonable_encoder(slug)}",
            method="POST",
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[BulkRuleResponseItem],
                    parse_obj_as(
                        type_=typing.List[BulkRuleResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def parallel_solve(
        self, *, request: ParallelSolveRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ParallelSolveResponse]:
        """
        Executes multiple rules or flows in parallel based on a provided mapping of rule/flow slugs to payloads.

        Parameters
        ----------
        request : ParallelSolveRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ParallelSolveResponse]
            Parallel execution successful. The response is an object mirroring the request structure, but providing each rule/flow's results instead.
        """
        _response = self._client_wrapper.httpx_client.request(
            "parallel-solve",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=ParallelSolveRequest, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ParallelSolveResponse,
                    parse_obj_as(
                        type_=ParallelSolveResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawRulesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def solve(
        self, slug: str, *, request: DynamicRequestPayload, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DynamicResponsePayload]:
        """
        Executes a single rule identified by a unique slug. The request and response formats are dynamic, dependent on the rule configuration.

        Parameters
        ----------
        slug : str
            The unique identifier for the resource.

        request : DynamicRequestPayload

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DynamicResponsePayload]
            Rule execution successful. The response structure depends on the rule configuration.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"solve/{jsonable_encoder(slug)}",
            method="POST",
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DynamicResponsePayload,
                    parse_obj_as(
                        type_=DynamicResponsePayload,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def bulk_solve(
        self,
        slug: str,
        *,
        request: typing.Sequence[DynamicRequestPayload],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[BulkRuleResponseItem]]:
        """
        Executes a particular rule against multiple request data payloads provided in a list.

        Parameters
        ----------
        slug : str
            The unique identifier for the resource.

        request : typing.Sequence[DynamicRequestPayload]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[BulkRuleResponseItem]]
            Bulk rule execution successful. The response is an array of results, each dependent on the rule configuration.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"bulk-solve/{jsonable_encoder(slug)}",
            method="POST",
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[BulkRuleResponseItem],
                    parse_obj_as(
                        type_=typing.List[BulkRuleResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def parallel_solve(
        self, *, request: ParallelSolveRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ParallelSolveResponse]:
        """
        Executes multiple rules or flows in parallel based on a provided mapping of rule/flow slugs to payloads.

        Parameters
        ----------
        request : ParallelSolveRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ParallelSolveResponse]
            Parallel execution successful. The response is an object mirroring the request structure, but providing each rule/flow's results instead.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "parallel-solve",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=ParallelSolveRequest, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ParallelSolveResponse,
                    parse_obj_as(
                        type_=ParallelSolveResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
