# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.scale_status_response import ScaleStatusResponse
from .raw_client import AsyncRawInfraClient, RawInfraClient


class InfraClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInfraClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInfraClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInfraClient
        """
        return self._raw_client

    def status(self, *, request_options: typing.Optional[RequestOptions] = None) -> ScaleStatusResponse:
        """
        Reports the fleet scale-up state. Worker counts reflect solvers that have actually joined the processing group and can accept work. Self-hosted deployments only.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScaleStatusResponse
            Current fleet scaling status.

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.infra.status()
        """
        _response = self._raw_client.status(request_options=request_options)
        return _response.data

    def scale(self, *, request_options: typing.Optional[RequestOptions] = None) -> ScaleStatusResponse:
        """
        Scales up the deployment's solver fleet to its maximum capacity ahead of a known incoming batch workload. Usually takes 1-2 minutes to complete. This is completely optional, the solver fleet will scale up automatically as needed anyway. Self-hosted deployments only.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScaleStatusResponse
            Warm-up requested (or refreshed). Returns the same status body as GET /scale.

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.infra.scale()
        """
        _response = self._raw_client.scale(request_options=request_options)
        return _response.data


class AsyncInfraClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInfraClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInfraClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInfraClient
        """
        return self._raw_client

    async def status(self, *, request_options: typing.Optional[RequestOptions] = None) -> ScaleStatusResponse:
        """
        Reports the fleet scale-up state. Worker counts reflect solvers that have actually joined the processing group and can accept work. Self-hosted deployments only.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScaleStatusResponse
            Current fleet scaling status.

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.infra.status()


        asyncio.run(main())
        """
        _response = await self._raw_client.status(request_options=request_options)
        return _response.data

    async def scale(self, *, request_options: typing.Optional[RequestOptions] = None) -> ScaleStatusResponse:
        """
        Scales up the deployment's solver fleet to its maximum capacity ahead of a known incoming batch workload. Usually takes 1-2 minutes to complete. This is completely optional, the solver fleet will scale up automatically as needed anyway. Self-hosted deployments only.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScaleStatusResponse
            Warm-up requested (or refreshed). Returns the same status body as GET /scale.

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.infra.scale()


        asyncio.run(main())
        """
        _response = await self._raw_client.scale(request_options=request_options)
        return _response.data
