# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.jsonable_encoder import jsonable_encoder
from ...core.pydantic_utilities import parse_obj_as
from ...core.request_options import RequestOptions
from ...core.serialization import convert_and_respect_annotation_metadata
from ...errors.bad_request_error import BadRequestError
from ...errors.internal_server_error import InternalServerError
from ...errors.not_found_error import NotFoundError
from ...types.context_detail import ContextDetail
from ...types.context_list_response import ContextListResponse
from ...types.create_context_response import CreateContextResponse
from ...types.delete_context_response import DeleteContextResponse
from ...types.update_context_response import UpdateContextResponse
from .types.create_context_request_on_schema_mismatch import CreateContextRequestOnSchemaMismatch
from .types.create_context_request_schema_item import CreateContextRequestSchemaItem
from .types.update_context_request_on_schema_mismatch import UpdateContextRequestOnSchemaMismatch
from .types.update_context_request_schema_item import UpdateContextRequestSchemaItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawObjectsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[ContextListResponse]:
        """
        Retrieve all contexts for the authenticated user.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ContextListResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "admin/contexts",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ContextListResponse,
                    parse_obj_as(
                        type_=ContextListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        name: str,
        schema: typing.Sequence[CreateContextRequestSchemaItem],
        identity_fact: str,
        slug: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        auto_execute_decisions: typing.Optional[bool] = OMIT,
        ttl_seconds: typing.Optional[int] = OMIT,
        history_limit: typing.Optional[int] = OMIT,
        on_schema_mismatch: typing.Optional[CreateContextRequestOnSchemaMismatch] = OMIT,
        webhook_on_solve: typing.Optional[str] = OMIT,
        webhook_on_expire: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateContextResponse]:
        """
        Create a new context for the authenticated user.

        Parameters
        ----------
        name : str
            The name of the context.

        schema : typing.Sequence[CreateContextRequestSchemaItem]
            Initial schema fields for the context. At least one field must be defined.

        identity_fact : str
            The field key to use as the unique identifier for instances. Must be a key from the schema.

        slug : typing.Optional[str]
            Optional custom slug. Auto-generated if not provided.

        description : typing.Optional[str]
            The description of the context.

        auto_execute_decisions : typing.Optional[bool]
            When true (default), bound rules and flows automatically execute when their inputs are satisfied.

        ttl_seconds : typing.Optional[int]
            Time-to-live in seconds for live context instances. Instances expire after this duration.

        history_limit : typing.Optional[int]
            Maximum number of history entries to retain per field.

        on_schema_mismatch : typing.Optional[CreateContextRequestOnSchemaMismatch]
            How to handle fields that don't match the schema.

        webhook_on_solve : typing.Optional[str]
            Webhook URL called when a rule or flow successfully solves.

        webhook_on_expire : typing.Optional[str]
            Webhook URL called when a live context expires due to TTL.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateContextResponse]
            Context created successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "admin/contexts",
            method="POST",
            json={
                "name": name,
                "slug": slug,
                "description": description,
                "schema": convert_and_respect_annotation_metadata(
                    object_=schema, annotation=typing.Sequence[CreateContextRequestSchemaItem], direction="write"
                ),
                "identity_fact": identity_fact,
                "auto_execute_decisions": auto_execute_decisions,
                "ttl_seconds": ttl_seconds,
                "history_limit": history_limit,
                "on_schema_mismatch": on_schema_mismatch,
                "webhook_on_solve": webhook_on_solve,
                "webhook_on_expire": webhook_on_expire,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateContextResponse,
                    parse_obj_as(
                        type_=CreateContextResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[ContextDetail]:
        """
        Retrieve a specific context by its ID.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ContextDetail]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"admin/contexts/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ContextDetail,
                    parse_obj_as(
                        type_=ContextDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        slug: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        schema: typing.Optional[typing.Sequence[UpdateContextRequestSchemaItem]] = OMIT,
        auto_execute_decisions: typing.Optional[bool] = OMIT,
        ttl_seconds: typing.Optional[int] = OMIT,
        history_limit: typing.Optional[int] = OMIT,
        on_schema_mismatch: typing.Optional[UpdateContextRequestOnSchemaMismatch] = OMIT,
        webhook_on_solve: typing.Optional[str] = OMIT,
        webhook_on_expire: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdateContextResponse]:
        """
        Update an existing context's properties and schema.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        name : typing.Optional[str]
            The name of the context.

        slug : typing.Optional[str]
            The slug of the context.

        description : typing.Optional[str]
            The description of the context.

        schema : typing.Optional[typing.Sequence[UpdateContextRequestSchemaItem]]
            Updated schema fields for the context.

        auto_execute_decisions : typing.Optional[bool]
            When true, bound rules and flows automatically execute when their inputs are satisfied.

        ttl_seconds : typing.Optional[int]
            Time-to-live in seconds for live context instances. Instances expire after this duration.

        history_limit : typing.Optional[int]
            Maximum number of history entries to retain per field.

        on_schema_mismatch : typing.Optional[UpdateContextRequestOnSchemaMismatch]
            How to handle fields that don't match the schema.

        webhook_on_solve : typing.Optional[str]
            Webhook URL called when a rule or flow successfully solves.

        webhook_on_expire : typing.Optional[str]
            Webhook URL called when a live context expires due to TTL.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdateContextResponse]
            Context updated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"admin/contexts/{jsonable_encoder(id)}",
            method="PUT",
            json={
                "name": name,
                "slug": slug,
                "description": description,
                "schema": convert_and_respect_annotation_metadata(
                    object_=schema, annotation=typing.Sequence[UpdateContextRequestSchemaItem], direction="write"
                ),
                "auto_execute_decisions": auto_execute_decisions,
                "ttl_seconds": ttl_seconds,
                "history_limit": history_limit,
                "on_schema_mismatch": on_schema_mismatch,
                "webhook_on_solve": webhook_on_solve,
                "webhook_on_expire": webhook_on_expire,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateContextResponse,
                    parse_obj_as(
                        type_=UpdateContextResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeleteContextResponse]:
        """
        Delete a specific context and all its instances.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeleteContextResponse]
            Context deleted successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"admin/contexts/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteContextResponse,
                    parse_obj_as(
                        type_=DeleteContextResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawObjectsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ContextListResponse]:
        """
        Retrieve all contexts for the authenticated user.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ContextListResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "admin/contexts",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ContextListResponse,
                    parse_obj_as(
                        type_=ContextListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        name: str,
        schema: typing.Sequence[CreateContextRequestSchemaItem],
        identity_fact: str,
        slug: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        auto_execute_decisions: typing.Optional[bool] = OMIT,
        ttl_seconds: typing.Optional[int] = OMIT,
        history_limit: typing.Optional[int] = OMIT,
        on_schema_mismatch: typing.Optional[CreateContextRequestOnSchemaMismatch] = OMIT,
        webhook_on_solve: typing.Optional[str] = OMIT,
        webhook_on_expire: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateContextResponse]:
        """
        Create a new context for the authenticated user.

        Parameters
        ----------
        name : str
            The name of the context.

        schema : typing.Sequence[CreateContextRequestSchemaItem]
            Initial schema fields for the context. At least one field must be defined.

        identity_fact : str
            The field key to use as the unique identifier for instances. Must be a key from the schema.

        slug : typing.Optional[str]
            Optional custom slug. Auto-generated if not provided.

        description : typing.Optional[str]
            The description of the context.

        auto_execute_decisions : typing.Optional[bool]
            When true (default), bound rules and flows automatically execute when their inputs are satisfied.

        ttl_seconds : typing.Optional[int]
            Time-to-live in seconds for live context instances. Instances expire after this duration.

        history_limit : typing.Optional[int]
            Maximum number of history entries to retain per field.

        on_schema_mismatch : typing.Optional[CreateContextRequestOnSchemaMismatch]
            How to handle fields that don't match the schema.

        webhook_on_solve : typing.Optional[str]
            Webhook URL called when a rule or flow successfully solves.

        webhook_on_expire : typing.Optional[str]
            Webhook URL called when a live context expires due to TTL.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateContextResponse]
            Context created successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "admin/contexts",
            method="POST",
            json={
                "name": name,
                "slug": slug,
                "description": description,
                "schema": convert_and_respect_annotation_metadata(
                    object_=schema, annotation=typing.Sequence[CreateContextRequestSchemaItem], direction="write"
                ),
                "identity_fact": identity_fact,
                "auto_execute_decisions": auto_execute_decisions,
                "ttl_seconds": ttl_seconds,
                "history_limit": history_limit,
                "on_schema_mismatch": on_schema_mismatch,
                "webhook_on_solve": webhook_on_solve,
                "webhook_on_expire": webhook_on_expire,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateContextResponse,
                    parse_obj_as(
                        type_=CreateContextResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ContextDetail]:
        """
        Retrieve a specific context by its ID.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ContextDetail]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"admin/contexts/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ContextDetail,
                    parse_obj_as(
                        type_=ContextDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        slug: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        schema: typing.Optional[typing.Sequence[UpdateContextRequestSchemaItem]] = OMIT,
        auto_execute_decisions: typing.Optional[bool] = OMIT,
        ttl_seconds: typing.Optional[int] = OMIT,
        history_limit: typing.Optional[int] = OMIT,
        on_schema_mismatch: typing.Optional[UpdateContextRequestOnSchemaMismatch] = OMIT,
        webhook_on_solve: typing.Optional[str] = OMIT,
        webhook_on_expire: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdateContextResponse]:
        """
        Update an existing context's properties and schema.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        name : typing.Optional[str]
            The name of the context.

        slug : typing.Optional[str]
            The slug of the context.

        description : typing.Optional[str]
            The description of the context.

        schema : typing.Optional[typing.Sequence[UpdateContextRequestSchemaItem]]
            Updated schema fields for the context.

        auto_execute_decisions : typing.Optional[bool]
            When true, bound rules and flows automatically execute when their inputs are satisfied.

        ttl_seconds : typing.Optional[int]
            Time-to-live in seconds for live context instances. Instances expire after this duration.

        history_limit : typing.Optional[int]
            Maximum number of history entries to retain per field.

        on_schema_mismatch : typing.Optional[UpdateContextRequestOnSchemaMismatch]
            How to handle fields that don't match the schema.

        webhook_on_solve : typing.Optional[str]
            Webhook URL called when a rule or flow successfully solves.

        webhook_on_expire : typing.Optional[str]
            Webhook URL called when a live context expires due to TTL.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdateContextResponse]
            Context updated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"admin/contexts/{jsonable_encoder(id)}",
            method="PUT",
            json={
                "name": name,
                "slug": slug,
                "description": description,
                "schema": convert_and_respect_annotation_metadata(
                    object_=schema, annotation=typing.Sequence[UpdateContextRequestSchemaItem], direction="write"
                ),
                "auto_execute_decisions": auto_execute_decisions,
                "ttl_seconds": ttl_seconds,
                "history_limit": history_limit,
                "on_schema_mismatch": on_schema_mismatch,
                "webhook_on_solve": webhook_on_solve,
                "webhook_on_expire": webhook_on_expire,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateContextResponse,
                    parse_obj_as(
                        type_=UpdateContextResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeleteContextResponse]:
        """
        Delete a specific context and all its instances.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeleteContextResponse]
            Context deleted successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"admin/contexts/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeleteContextResponse,
                    parse_obj_as(
                        type_=DeleteContextResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
