# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.usage_statistics import UsageStatistics
from .raw_client import AsyncRawAssetsClient, RawAssetsClient
from .types.export_manifest_request_root_type import ExportManifestRequestRootType
from .types.export_rbm_assets_response import ExportRbmAssetsResponse
from .types.import_rbm_assets_response import ImportRbmAssetsResponse

if typing.TYPE_CHECKING:
    from .contexts.client import AsyncContextsClient, ContextsClient
    from .flows.client import AsyncFlowsClient, FlowsClient
    from .folders.client import AsyncFoldersClient, FoldersClient
    from .rules.client import AsyncRulesClient, RulesClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AssetsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAssetsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._rules: typing.Optional[RulesClient] = None
        self._flows: typing.Optional[FlowsClient] = None
        self._folders: typing.Optional[FoldersClient] = None
        self._contexts: typing.Optional[ContextsClient] = None

    @property
    def with_raw_response(self) -> RawAssetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAssetsClient
        """
        return self._raw_client

    def get_usage(self, *, request_options: typing.Optional[RequestOptions] = None) -> UsageStatistics:
        """
        Get the rule execution usage of your organization.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UsageStatistics
            Success

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.assets.get_usage()
        """
        _response = self._raw_client.get_usage(request_options=request_options)
        return _response.data

    def import_rbm(
        self,
        *,
        request: typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ImportRbmAssetsResponse:
        """
        Import rules, flows, contexts, and values from a Rulebricks manifest file (*.rbm). Plain JSON remains supported, and clients may send the same JSON envelope gzip-compressed with `Content-Type: application/octet-stream` and `X-Rulebricks-Content-Encoding: gzip`.

        Parameters
        ----------
        request : typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ImportRbmAssetsResponse
            Import completed, or a write-free import plan was returned when `preview_only` is true.

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.assets.import_rbm()
        """
        _response = self._raw_client.import_rbm(request=request, request_options=request_options)
        return _response.data

    def export_rbm(
        self,
        *,
        root_type: ExportManifestRequestRootType,
        root_ids: typing.Sequence[str],
        include_downstream: typing.Optional[bool] = OMIT,
        manifest_name: typing.Optional[str] = OMIT,
        manifest_description: typing.Optional[str] = OMIT,
        preview_only: typing.Optional[bool] = OMIT,
        compress: typing.Optional[bool] = OMIT,
        download: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExportRbmAssetsResponse:
        """
        Export selected rules, flows, contexts, and values to a Rulebricks manifest file (*.rbm). Dependencies are resolved automatically: exporting a flow includes its rules, contexts, vocabulary values, and any flows referenced by Run Flow nodes (recursively). Set `compress: true` to receive the manifest in compressed form (a compress-json array). Set `download: true` to receive that manifest directly as a streamed attachment instead of inside the `{ success, manifest }` envelope.

        Parameters
        ----------
        root_type : ExportManifestRequestRootType
            The type of root asset to export. All dependencies will be included.

        root_ids : typing.Sequence[str]
            Array of IDs for the root assets to export. Dependencies are automatically resolved.

        include_downstream : typing.Optional[bool]
            For context exports, whether to include rules and flows bound to the context.

        manifest_name : typing.Optional[str]
            Optional name for the exported manifest.

        manifest_description : typing.Optional[str]
            Optional description for the exported manifest.

        preview_only : typing.Optional[bool]
            If true, returns a preview of what would be exported without the full data.

        compress : typing.Optional[bool]
            If true, the manifest in the response is returned in compressed form: the JSON array produced by the compress-json library instead of a plain object. Compressed manifests are substantially smaller, can be saved directly as a .rbm file, and are accepted by the import endpoint as-is. Intended for raw HTTP usage and file tooling; typed SDK clients should omit this flag, since the generated response type models the manifest as an object.

        download : typing.Optional[bool]
            If true, returns the manifest itself as a streamed application/json attachment with Content-Disposition, rather than the normal `{ success, manifest }` response envelope. Combine with `compress: true` for large .rbm downloads.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExportRbmAssetsResponse
            Export completed successfully. With `download: true`, the response body is the raw manifest (or compress-json array) and `Content-Disposition` names the `.rbm` attachment; otherwise the documented JSON envelope is returned.

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.assets.export_rbm(
            root_type="rule",
            root_ids=["pricing-rule", "eligibility-check"],
            include_downstream=False,
        )
        """
        _response = self._raw_client.export_rbm(
            root_type=root_type,
            root_ids=root_ids,
            include_downstream=include_downstream,
            manifest_name=manifest_name,
            manifest_description=manifest_description,
            preview_only=preview_only,
            compress=compress,
            download=download,
            request_options=request_options,
        )
        return _response.data

    @property
    def rules(self) -> RulesClient:
        if self._rules is None:
            from .rules.client import RulesClient  # noqa: E402

            self._rules = RulesClient(client_wrapper=self._client_wrapper)
        return self._rules

    @property
    def flows(self) -> FlowsClient:
        if self._flows is None:
            from .flows.client import FlowsClient  # noqa: E402

            self._flows = FlowsClient(client_wrapper=self._client_wrapper)
        return self._flows

    @property
    def folders(self) -> FoldersClient:
        if self._folders is None:
            from .folders.client import FoldersClient  # noqa: E402

            self._folders = FoldersClient(client_wrapper=self._client_wrapper)
        return self._folders

    @property
    def contexts(self) -> ContextsClient:
        if self._contexts is None:
            from .contexts.client import ContextsClient  # noqa: E402

            self._contexts = ContextsClient(client_wrapper=self._client_wrapper)
        return self._contexts


class AsyncAssetsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAssetsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._rules: typing.Optional[AsyncRulesClient] = None
        self._flows: typing.Optional[AsyncFlowsClient] = None
        self._folders: typing.Optional[AsyncFoldersClient] = None
        self._contexts: typing.Optional[AsyncContextsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawAssetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAssetsClient
        """
        return self._raw_client

    async def get_usage(self, *, request_options: typing.Optional[RequestOptions] = None) -> UsageStatistics:
        """
        Get the rule execution usage of your organization.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UsageStatistics
            Success

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.assets.get_usage()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_usage(request_options=request_options)
        return _response.data

    async def import_rbm(
        self,
        *,
        request: typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ImportRbmAssetsResponse:
        """
        Import rules, flows, contexts, and values from a Rulebricks manifest file (*.rbm). Plain JSON remains supported, and clients may send the same JSON envelope gzip-compressed with `Content-Type: application/octet-stream` and `X-Rulebricks-Content-Encoding: gzip`.

        Parameters
        ----------
        request : typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ImportRbmAssetsResponse
            Import completed, or a write-free import plan was returned when `preview_only` is true.

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.assets.import_rbm()


        asyncio.run(main())
        """
        _response = await self._raw_client.import_rbm(request=request, request_options=request_options)
        return _response.data

    async def export_rbm(
        self,
        *,
        root_type: ExportManifestRequestRootType,
        root_ids: typing.Sequence[str],
        include_downstream: typing.Optional[bool] = OMIT,
        manifest_name: typing.Optional[str] = OMIT,
        manifest_description: typing.Optional[str] = OMIT,
        preview_only: typing.Optional[bool] = OMIT,
        compress: typing.Optional[bool] = OMIT,
        download: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExportRbmAssetsResponse:
        """
        Export selected rules, flows, contexts, and values to a Rulebricks manifest file (*.rbm). Dependencies are resolved automatically: exporting a flow includes its rules, contexts, vocabulary values, and any flows referenced by Run Flow nodes (recursively). Set `compress: true` to receive the manifest in compressed form (a compress-json array). Set `download: true` to receive that manifest directly as a streamed attachment instead of inside the `{ success, manifest }` envelope.

        Parameters
        ----------
        root_type : ExportManifestRequestRootType
            The type of root asset to export. All dependencies will be included.

        root_ids : typing.Sequence[str]
            Array of IDs for the root assets to export. Dependencies are automatically resolved.

        include_downstream : typing.Optional[bool]
            For context exports, whether to include rules and flows bound to the context.

        manifest_name : typing.Optional[str]
            Optional name for the exported manifest.

        manifest_description : typing.Optional[str]
            Optional description for the exported manifest.

        preview_only : typing.Optional[bool]
            If true, returns a preview of what would be exported without the full data.

        compress : typing.Optional[bool]
            If true, the manifest in the response is returned in compressed form: the JSON array produced by the compress-json library instead of a plain object. Compressed manifests are substantially smaller, can be saved directly as a .rbm file, and are accepted by the import endpoint as-is. Intended for raw HTTP usage and file tooling; typed SDK clients should omit this flag, since the generated response type models the manifest as an object.

        download : typing.Optional[bool]
            If true, returns the manifest itself as a streamed application/json attachment with Content-Disposition, rather than the normal `{ success, manifest }` response envelope. Combine with `compress: true` for large .rbm downloads.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExportRbmAssetsResponse
            Export completed successfully. With `download: true`, the response body is the raw manifest (or compress-json array) and `Content-Disposition` names the `.rbm` attachment; otherwise the documented JSON envelope is returned.

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.assets.export_rbm(
                root_type="rule",
                root_ids=["pricing-rule", "eligibility-check"],
                include_downstream=False,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.export_rbm(
            root_type=root_type,
            root_ids=root_ids,
            include_downstream=include_downstream,
            manifest_name=manifest_name,
            manifest_description=manifest_description,
            preview_only=preview_only,
            compress=compress,
            download=download,
            request_options=request_options,
        )
        return _response.data

    @property
    def rules(self) -> AsyncRulesClient:
        if self._rules is None:
            from .rules.client import AsyncRulesClient  # noqa: E402

            self._rules = AsyncRulesClient(client_wrapper=self._client_wrapper)
        return self._rules

    @property
    def flows(self) -> AsyncFlowsClient:
        if self._flows is None:
            from .flows.client import AsyncFlowsClient  # noqa: E402

            self._flows = AsyncFlowsClient(client_wrapper=self._client_wrapper)
        return self._flows

    @property
    def folders(self) -> AsyncFoldersClient:
        if self._folders is None:
            from .folders.client import AsyncFoldersClient  # noqa: E402

            self._folders = AsyncFoldersClient(client_wrapper=self._client_wrapper)
        return self._folders

    @property
    def contexts(self) -> AsyncContextsClient:
        if self._contexts is None:
            from .contexts.client import AsyncContextsClient  # noqa: E402

            self._contexts = AsyncContextsClient(client_wrapper=self._client_wrapper)
        return self._contexts
