# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.delete_object_response import DeleteObjectResponse
from ..types.upsert_object_request import UpsertObjectRequest
from ..types.upsert_object_response import UpsertObjectResponse
from ..types.workspace_object import WorkspaceObject
from .raw_client import AsyncRawObjectsClient, RawObjectsClient
from .types.delete_objects_request_values import DeleteObjectsRequestValues

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ObjectsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawObjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawObjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawObjectsClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[WorkspaceObject]:
        """
        Lists the workspace's objects (JSON Schemas). The provided API key must have permission to view vocabulary values. Results are scoped to the API key holder's user groups.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[WorkspaceObject]
            Success

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.objects.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def upsert(
        self, *, request: UpsertObjectRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpsertObjectResponse:
        """
        Creates or updates an object by ID or name and syncs enum values it generates. `content` and at least one of `id` or `name` are required. Objects help workspace admins programmatically determine multiple collections of values based on Rulebricks' contracts with external systems from a single JSON Schema source. Renaming the object's display name does not move its managed collection paths: those paths derive from schema field keys. When a schema field key itself is renamed, `field_rename` can preserve the generated values' identities.

        Parameters
        ----------
        request : UpsertObjectRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpsertObjectResponse
            Object updated and its managed values synced.

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.objects.upsert(
            request={
                "name": "Claim",
                "content": '{\n  "type": "object",\n  "properties": {\n    "countryCode": { "type": "string", "title": "Country Code", "enum": ["US", "CA", "GB"] }\n  }\n}',
                "user_groups": ["underwriting"],
            },
        )
        """
        _response = self._raw_client.upsert(request=request, request_options=request_options)
        return _response.data

    def get(self, object_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WorkspaceObject:
        """
        Fetches one object by ID or exact name. The provided API key must have permission to view vocabulary values.

        Parameters
        ----------
        object_id : str
            Object ID or exact name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkspaceObject
            Success

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.objects.get(
            object_id="objectId",
        )
        """
        _response = self._raw_client.get(object_id, request_options=request_options)
        return _response.data

    def delete(
        self,
        object_id: str,
        *,
        values: typing.Optional[DeleteObjectsRequestValues] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteObjectResponse:
        """
        Deletes the object. By default, unused values are permanently deleted while values referenced by draft, current, or historical rules, flows, or other vocabulary values are archived. Pass values=detach to keep every generated value active as an ordinary, hand-editable value.

        Parameters
        ----------
        object_id : str
            Object ID or exact name

        values : typing.Optional[DeleteObjectsRequestValues]
            What happens to generated values: 'archive' (default) permanently deletes unused values and archives referenced values; 'detach' retains all values as active ordinary values.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteObjectResponse
            Deleted

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.objects.delete(
            object_id="objectId",
        )
        """
        _response = self._raw_client.delete(object_id, values=values, request_options=request_options)
        return _response.data


class AsyncObjectsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawObjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawObjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawObjectsClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[WorkspaceObject]:
        """
        Lists the workspace's objects (JSON Schemas). The provided API key must have permission to view vocabulary values. Results are scoped to the API key holder's user groups.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[WorkspaceObject]
            Success

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.objects.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def upsert(
        self, *, request: UpsertObjectRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpsertObjectResponse:
        """
        Creates or updates an object by ID or name and syncs enum values it generates. `content` and at least one of `id` or `name` are required. Objects help workspace admins programmatically determine multiple collections of values based on Rulebricks' contracts with external systems from a single JSON Schema source. Renaming the object's display name does not move its managed collection paths: those paths derive from schema field keys. When a schema field key itself is renamed, `field_rename` can preserve the generated values' identities.

        Parameters
        ----------
        request : UpsertObjectRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpsertObjectResponse
            Object updated and its managed values synced.

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.objects.upsert(
                request={
                    "name": "Claim",
                    "content": '{\n  "type": "object",\n  "properties": {\n    "countryCode": { "type": "string", "title": "Country Code", "enum": ["US", "CA", "GB"] }\n  }\n}',
                    "user_groups": ["underwriting"],
                },
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upsert(request=request, request_options=request_options)
        return _response.data

    async def get(self, object_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WorkspaceObject:
        """
        Fetches one object by ID or exact name. The provided API key must have permission to view vocabulary values.

        Parameters
        ----------
        object_id : str
            Object ID or exact name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkspaceObject
            Success

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.objects.get(
                object_id="objectId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(object_id, request_options=request_options)
        return _response.data

    async def delete(
        self,
        object_id: str,
        *,
        values: typing.Optional[DeleteObjectsRequestValues] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteObjectResponse:
        """
        Deletes the object. By default, unused values are permanently deleted while values referenced by draft, current, or historical rules, flows, or other vocabulary values are archived. Pass values=detach to keep every generated value active as an ordinary, hand-editable value.

        Parameters
        ----------
        object_id : str
            Object ID or exact name

        values : typing.Optional[DeleteObjectsRequestValues]
            What happens to generated values: 'archive' (default) permanently deletes unused values and archives referenced values; 'detach' retains all values as active ordinary values.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteObjectResponse
            Deleted

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.objects.delete(
                object_id="objectId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(object_id, values=values, request_options=request_options)
        return _response.data
