# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.delete_object_response import DeleteObjectResponse
from ..types.upsert_object_response import UpsertObjectResponse
from ..types.workspace_object import WorkspaceObject
from .raw_client import AsyncRawObjectsClient, RawObjectsClient
from .types.delete_objects_request_values import DeleteObjectsRequestValues

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ObjectsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawObjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawObjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawObjectsClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[WorkspaceObject]:
        """
        Lists the workspace's objects (JSON Schemas). Results are scoped to the API key holder's user groups, matching the visibility model of values, rules, and flows: group-restricted keys only see objects whose user_groups overlap theirs.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[WorkspaceObject]
            Success

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.objects.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def upsert(
        self,
        *,
        content: str,
        id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        user_groups: typing.Optional[typing.Sequence[str]] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        expected_updated_at: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpsertObjectResponse:
        """
        Creates or updates an object by ID or name and syncs enum values it generates. Objects help workspace admins programmatically determine multiple collections of values based on Rulebricks' contracts with external systems from a single JSON Schema source.

        Parameters
        ----------
        content : str
            The object's JSON Schema as a string. Enums in the schema become the object's managed values.

        id : typing.Optional[str]
            Object ID to update. Omit to resolve by name (creating the object when the name is new).

        name : typing.Optional[str]
            Object name. Required when ID is omitted; used to resolve the existing object or to name a new one.

        user_groups : typing.Optional[typing.Sequence[str]]
            User groups for the object, propagated to every value it generates. Omit to keep the current groups.

        dry_run : typing.Optional[bool]
            Preview the value diff (would_sync / would_archive) without writing anything.

        expected_updated_at : typing.Optional[str]
            Optimistic concurrency: reject with 409 when the object's updated_at no longer matches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpsertObjectResponse
            Object updated and its managed values synced.

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.objects.upsert(
            name="Claim",
            content='{\n  "type": "object",\n  "properties": {\n    "countryCode": { "type": "string", "title": "Country Code", "enum": ["US", "CA", "GB"] }\n  }\n}',
            user_groups=["underwriting"],
        )
        """
        _response = self._raw_client.upsert(
            content=content,
            id=id,
            name=name,
            user_groups=user_groups,
            dry_run=dry_run,
            expected_updated_at=expected_updated_at,
            request_options=request_options,
        )
        return _response.data

    def get(self, object_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WorkspaceObject:
        """
        Fetches one object by ID or exact name.

        Parameters
        ----------
        object_id : str
            Object ID or exact name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkspaceObject
            Success

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.objects.get(
            object_id="objectId",
        )
        """
        _response = self._raw_client.get(object_id, request_options=request_options)
        return _response.data

    def delete(
        self,
        object_id: str,
        *,
        values: typing.Optional[DeleteObjectsRequestValues] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteObjectResponse:
        """
        Deletes the object. Its generated values always lose their management lock; by default they are also archived (published rules keep resolving them by id). Pass values=detach to keep them active as ordinary, hand-editable values instead. Requires the manage objects entitlement.

        Parameters
        ----------
        object_id : str
            Object ID or exact name

        values : typing.Optional[DeleteObjectsRequestValues]
            What happens to the values this object generated: 'archive' (default) or 'detach'.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteObjectResponse
            Deleted

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.objects.delete(
            object_id="objectId",
        )
        """
        _response = self._raw_client.delete(object_id, values=values, request_options=request_options)
        return _response.data


class AsyncObjectsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawObjectsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawObjectsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawObjectsClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[WorkspaceObject]:
        """
        Lists the workspace's objects (JSON Schemas). Results are scoped to the API key holder's user groups, matching the visibility model of values, rules, and flows: group-restricted keys only see objects whose user_groups overlap theirs.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[WorkspaceObject]
            Success

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.objects.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def upsert(
        self,
        *,
        content: str,
        id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        user_groups: typing.Optional[typing.Sequence[str]] = OMIT,
        dry_run: typing.Optional[bool] = OMIT,
        expected_updated_at: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpsertObjectResponse:
        """
        Creates or updates an object by ID or name and syncs enum values it generates. Objects help workspace admins programmatically determine multiple collections of values based on Rulebricks' contracts with external systems from a single JSON Schema source.

        Parameters
        ----------
        content : str
            The object's JSON Schema as a string. Enums in the schema become the object's managed values.

        id : typing.Optional[str]
            Object ID to update. Omit to resolve by name (creating the object when the name is new).

        name : typing.Optional[str]
            Object name. Required when ID is omitted; used to resolve the existing object or to name a new one.

        user_groups : typing.Optional[typing.Sequence[str]]
            User groups for the object, propagated to every value it generates. Omit to keep the current groups.

        dry_run : typing.Optional[bool]
            Preview the value diff (would_sync / would_archive) without writing anything.

        expected_updated_at : typing.Optional[str]
            Optimistic concurrency: reject with 409 when the object's updated_at no longer matches.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpsertObjectResponse
            Object updated and its managed values synced.

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.objects.upsert(
                name="Claim",
                content='{\n  "type": "object",\n  "properties": {\n    "countryCode": { "type": "string", "title": "Country Code", "enum": ["US", "CA", "GB"] }\n  }\n}',
                user_groups=["underwriting"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upsert(
            content=content,
            id=id,
            name=name,
            user_groups=user_groups,
            dry_run=dry_run,
            expected_updated_at=expected_updated_at,
            request_options=request_options,
        )
        return _response.data

    async def get(self, object_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WorkspaceObject:
        """
        Fetches one object by ID or exact name.

        Parameters
        ----------
        object_id : str
            Object ID or exact name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkspaceObject
            Success

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.objects.get(
                object_id="objectId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(object_id, request_options=request_options)
        return _response.data

    async def delete(
        self,
        object_id: str,
        *,
        values: typing.Optional[DeleteObjectsRequestValues] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteObjectResponse:
        """
        Deletes the object. Its generated values always lose their management lock; by default they are also archived (published rules keep resolving them by id). Pass values=detach to keep them active as ordinary, hand-editable values instead. Requires the manage objects entitlement.

        Parameters
        ----------
        object_id : str
            Object ID or exact name

        values : typing.Optional[DeleteObjectsRequestValues]
            What happens to the values this object generated: 'archive' (default) or 'detach'.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteObjectResponse
            Deleted

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.objects.delete(
                object_id="objectId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(object_id, values=values, request_options=request_options)
        return _response.data
