# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_user_response import CreateUserResponse
from ..types.user_invite_response import UserInviteResponse
from ..types.user_list_response import UserListResponse
from .raw_client import AsyncRawUsersClient, RawUsersClient
from .types.user_invite_request_role import UserInviteRequestRole

if typing.TYPE_CHECKING:
    from .groups.client import AsyncGroupsClient, GroupsClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UsersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUsersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._groups: typing.Optional[GroupsClient] = None

    @property
    def with_raw_response(self) -> RawUsersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUsersClient
        """
        return self._raw_client

    def invite(
        self,
        *,
        email: str,
        role: typing.Optional[UserInviteRequestRole] = OMIT,
        user_groups: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UserInviteResponse:
        """
        Invite a new user to the organization or update role or user group data for an existing user.

        Parameters
        ----------
        email : str
            Email of the user to invite.

        role : typing.Optional[UserInviteRequestRole]
            System or custom role ID to assign to the user. Available system roles include 'admin', 'editor', and 'developer'.

        user_groups : typing.Optional[typing.Sequence[str]]
            List of user group names or IDs to assign to the user. All specified groups must exist in your organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserInviteResponse
            Invite successful or permissions updated successfully.

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.users.invite(
            email="newuser@example.com",
            role="developer",
            user_groups=["group1", "group2"],
        )
        """
        _response = self._raw_client.invite(
            email=email, role=role, user_groups=user_groups, request_options=request_options
        )
        return _response.data

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> UserListResponse:
        """
        List all users (including the admin and all team members) in the organization with their details including email, name, API key, role, user groups, and join date.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserListResponse
            List of users in the organization.

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.users.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        email: str,
        password: str,
        name: typing.Optional[str] = OMIT,
        role: typing.Optional[str] = OMIT,
        user_groups: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateUserResponse:
        """
        Create a new user directly with a password, bypassing the email invitation flow. The user can immediately log in with the provided credentials.

        Parameters
        ----------
        email : str
            Email address for the new user.

        password : str
            Password for the new user (minimum 8 characters). The user can log in immediately with this password.

        name : typing.Optional[str]
            Display name for the user.

        role : typing.Optional[str]
            Role to assign to the user. Defaults to 'developer' if not specified.

        user_groups : typing.Optional[typing.Sequence[str]]
            List of user group names or IDs to assign to the user.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateUserResponse
            User created successfully.

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.users.create(
            email="newuser@example.com",
            password="securePassword123",
        )
        """
        _response = self._raw_client.create(
            email=email,
            password=password,
            name=name,
            role=role,
            user_groups=user_groups,
            request_options=request_options,
        )
        return _response.data

    @property
    def groups(self):
        if self._groups is None:
            from .groups.client import GroupsClient  # noqa: E402

            self._groups = GroupsClient(client_wrapper=self._client_wrapper)
        return self._groups


class AsyncUsersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUsersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._groups: typing.Optional[AsyncGroupsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawUsersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUsersClient
        """
        return self._raw_client

    async def invite(
        self,
        *,
        email: str,
        role: typing.Optional[UserInviteRequestRole] = OMIT,
        user_groups: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UserInviteResponse:
        """
        Invite a new user to the organization or update role or user group data for an existing user.

        Parameters
        ----------
        email : str
            Email of the user to invite.

        role : typing.Optional[UserInviteRequestRole]
            System or custom role ID to assign to the user. Available system roles include 'admin', 'editor', and 'developer'.

        user_groups : typing.Optional[typing.Sequence[str]]
            List of user group names or IDs to assign to the user. All specified groups must exist in your organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserInviteResponse
            Invite successful or permissions updated successfully.

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.users.invite(
                email="newuser@example.com",
                role="developer",
                user_groups=["group1", "group2"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.invite(
            email=email, role=role, user_groups=user_groups, request_options=request_options
        )
        return _response.data

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> UserListResponse:
        """
        List all users (including the admin and all team members) in the organization with their details including email, name, API key, role, user groups, and join date.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserListResponse
            List of users in the organization.

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.users.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        email: str,
        password: str,
        name: typing.Optional[str] = OMIT,
        role: typing.Optional[str] = OMIT,
        user_groups: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateUserResponse:
        """
        Create a new user directly with a password, bypassing the email invitation flow. The user can immediately log in with the provided credentials.

        Parameters
        ----------
        email : str
            Email address for the new user.

        password : str
            Password for the new user (minimum 8 characters). The user can log in immediately with this password.

        name : typing.Optional[str]
            Display name for the user.

        role : typing.Optional[str]
            Role to assign to the user. Defaults to 'developer' if not specified.

        user_groups : typing.Optional[typing.Sequence[str]]
            List of user group names or IDs to assign to the user.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateUserResponse
            User created successfully.

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.users.create(
                email="newuser@example.com",
                password="securePassword123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            email=email,
            password=password,
            name=name,
            role=role,
            user_groups=user_groups,
            request_options=request_options,
        )
        return _response.data

    @property
    def groups(self):
        if self._groups is None:
            from .groups.client import AsyncGroupsClient  # noqa: E402

            self._groups = AsyncGroupsClient(client_wrapper=self._client_wrapper)
        return self._groups
