# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .context_base_on_schema_mismatch import ContextBaseOnSchemaMismatch


class ContextBase(UniversalBaseModel):
    """
    Base properties for a context.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier for the context.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the context.
    """

    slug: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique slug for the context used in API requests.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    The description of the context.
    """

    auto_execute_decisions: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, bound rules and flows automatically execute when their inputs are satisfied. When false, users must manually call /solve or /flows endpoints.
    """

    ttl_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Time-to-live in seconds for live context instances. Instances expire after this duration.
    """

    history_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of history entries to retain per field.
    """

    on_schema_mismatch: typing.Optional[ContextBaseOnSchemaMismatch] = pydantic.Field(default=None)
    """
    How to handle fields that don't match the schema: 'ignore' filters them out, 'reject' returns an error.
    """

    webhook_on_solve: typing.Optional[str] = pydantic.Field(default=None)
    """
    Webhook URL called when a rule or flow successfully solves for a live context.
    """

    webhook_on_expire: typing.Optional[str] = pydantic.Field(default=None)
    """
    Webhook URL called when a live context expires due to TTL.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
