# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .context_relationship_base_relation_type import ContextRelationshipBaseRelationType


class ContextRelationshipBase(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier for the relationship.
    """

    relation_type: typing.Optional[ContextRelationshipBaseRelationType] = pydantic.Field(default=None)
    """
    The type of relationship.
    """

    foreign_key_fact: typing.Optional[str] = pydantic.Field(default=None)
    """
    The field key used as the foreign key.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Runtime relationship key used by derived expressions. It is normalized to lowercase snake_case.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description of the relationship.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the relationship was created.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
