# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from .context_base import ContextBase
from .context_detail_bound_flows_item import ContextDetailBoundFlowsItem
from .context_detail_bound_rules_item import ContextDetailBoundRulesItem
from .context_detail_folder import ContextDetailFolder
from .context_detail_relationships import ContextDetailRelationships
from .context_schema import ContextSchema


class ContextDetail(ContextBase):
    schema_: typing_extensions.Annotated[typing.Optional[ContextSchema], FieldMetadata(alias="schema")] = None
    identity_fact: typing.Optional[str] = pydantic.Field(default=None)
    """
    The field key used as the unique identifier for instances.
    """

    user_groups: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    User groups that can interact with this context.
    """

    folder: typing.Optional[ContextDetailFolder] = pydantic.Field(default=None)
    """
    Folder/tag this context belongs to.
    """

    bound_rules: typing.Optional[typing.List[ContextDetailBoundRulesItem]] = pydantic.Field(default=None)
    """
    Rules bound to this context.
    """

    bound_flows: typing.Optional[typing.List[ContextDetailBoundFlowsItem]] = pydantic.Field(default=None)
    """
    Flows bound to this context (via their origin rule).
    """

    relationships: typing.Optional[ContextDetailRelationships] = None
    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the context was created.
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the context was last updated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
