# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .context_relationship_base import ContextRelationshipBase
from .context_relationship_incoming_source_context import ContextRelationshipIncomingSourceContext


class ContextRelationshipIncoming(ContextRelationshipBase):
    source_context: typing.Optional[ContextRelationshipIncomingSourceContext] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
