# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from .context_base import ContextBase
from .context_list_item_folder import ContextListItemFolder
from .context_schema import ContextSchema


class ContextListItem(ContextBase):
    """
    Summary of a context for listing. Uses counts instead of full arrays.
    """

    identity_fact: typing.Optional[str] = pydantic.Field(default=None)
    """
    The field key used as the unique identifier for instances.
    """

    schema_: typing_extensions.Annotated[typing.Optional[ContextSchema], FieldMetadata(alias="schema")] = None
    folder: typing.Optional[ContextListItemFolder] = None
    bound_rules_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of rules bound to this context.
    """

    bound_flows_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of flows bound to this context.
    """

    relationships_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of relationships for this context.
    """

    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
