# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateUserResponseUser(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the created user.
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address of the created user.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name of the user.
    """

    role: typing.Optional[str] = pydantic.Field(default=None)
    """
    Role assigned to the user.
    """

    user_groups: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    User groups assigned to the user.
    """

    api_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    API key generated for the user.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
