# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DeleteContextResponse(UniversalBaseModel):
    """
    Response after deleting a context.
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Success message.
    """

    unbound_rules: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Slugs of rules that were unbound from the deleted context.
    """

    unbound_flows: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Slugs of flows that were unbound from the deleted context.
    """

    pending_evaluations_cancelled: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of pending evaluations that were cancelled when the context was deleted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
