# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .export_manifest_response_manifest import ExportManifestResponseManifest


class ExportManifestResponse(UniversalBaseModel):
    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the export completed successfully.
    """

    manifest: typing.Optional[ExportManifestResponseManifest] = pydantic.Field(default=None)
    """
    The exported manifest data.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message if export failed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
