# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .export_manifest_preview_response_preview_counts import ExportManifestPreviewResponsePreviewCounts
from .export_manifest_preview_response_preview_items import ExportManifestPreviewResponsePreviewItems


class ExportManifestPreviewResponsePreview(UniversalBaseModel):
    """
    Preview of assets that would be exported. The preview wrapper uses snake_case, while asset items intentionally preserve `.rbm`/database casing (for example, `valueType` and `updatedAt`) because the same items feed manifest preview/import UI.
    """

    counts: typing.Optional[ExportManifestPreviewResponsePreviewCounts] = None
    items: typing.Optional[ExportManifestPreviewResponsePreviewItems] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
