# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .manifest_labeled_asset import ManifestLabeledAsset


class ExportManifestResponseManifest(UniversalBaseModel):
    """
    The exported manifest data. The wrapper uses snake_case, while asset objects inside `contexts`, `values`, `rules`, and `flows` intentionally preserve `.rbm`/database casing for round-trip compatibility. When the request sets `compress: true`, this field is instead the compress-json array encoding of the same manifest (a JSON array, not the object described below).
    """

    schema_version: typing.Optional[int] = pydantic.Field(default=None)
    """
    RBM schema version.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Manifest name.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Manifest description.
    """

    exported_at: typing.Optional[dt.datetime] = None
    exported_from: typing.Optional[str] = pydantic.Field(default=None)
    """
    Source workspace identifier.
    """

    contexts: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Exported contexts.
    """

    values: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Exported vocabulary values.
    """

    rules: typing.Optional[typing.List[ManifestLabeledAsset]] = pydantic.Field(default=None)
    """
    Exported rules.
    """

    flows: typing.Optional[typing.List[ManifestLabeledAsset]] = pydantic.Field(default=None)
    """
    Exported flows.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
