# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FlowDetailContext(UniversalBaseModel):
    """
    The context this flow is bound to (via its origin rule). Flows inherit context binding from their origin rule.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The context ID.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The context name.
    """

    slug: typing.Optional[str] = pydantic.Field(default=None)
    """
    The context slug.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
