# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .import_manifest_preview_response_preview_items_item import ImportManifestPreviewResponsePreviewItemsItem
from .import_manifest_preview_response_preview_policy import ImportManifestPreviewResponsePreviewPolicy


class ImportManifestPreviewResponsePreview(UniversalBaseModel):
    policy: ImportManifestPreviewResponsePreviewPolicy
    executable: bool
    partial: typing.Optional[bool] = None
    summary: typing.Dict[str, int]
    items: typing.List[ImportManifestPreviewResponsePreviewItemsItem]
    issues: typing.List[typing.Dict[str, typing.Any]]
    warnings: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
