# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ImportManifestResponseCreatedItem(UniversalBaseModel):
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Asset type (context, value, rule, flow, relationship).
    """

    stable_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stable ID of asset.
    """

    db_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Database ID of asset.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Import status.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
