# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .import_manifest_response_created_item import ImportManifestResponseCreatedItem
from .import_manifest_response_errors_item import ImportManifestResponseErrorsItem
from .import_manifest_response_organization_created import ImportManifestResponseOrganizationCreated
from .import_manifest_response_skipped_item import ImportManifestResponseSkippedItem
from .import_manifest_response_updated_item import ImportManifestResponseUpdatedItem


class ImportManifestResponse(UniversalBaseModel):
    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the import completed successfully.
    """

    created: typing.Optional[typing.List[ImportManifestResponseCreatedItem]] = pydantic.Field(default=None)
    """
    Assets that were created during import.
    """

    updated: typing.Optional[typing.List[ImportManifestResponseUpdatedItem]] = pydantic.Field(default=None)
    """
    Assets that were updated during import.
    """

    skipped: typing.Optional[typing.List[ImportManifestResponseSkippedItem]] = pydantic.Field(default=None)
    """
    Assets that were skipped during import.
    """

    errors: typing.Optional[typing.List[ImportManifestResponseErrorsItem]] = pydantic.Field(default=None)
    """
    Any errors encountered during import.
    """

    warnings: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Non-fatal warnings from import validation.
    """

    organization_created: typing.Optional[ImportManifestResponseOrganizationCreated] = pydantic.Field(default=None)
    """
    IDs of any organizational folders created during import.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
