# This file was auto-generated by Fern from our API Definition.

import typing

from .parallel_solve_request_value import ParallelSolveRequestValue

ParallelSolveRequest = typing.Dict[str, ParallelSolveRequestValue]
