# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .parallel_solve_entity_error_error import ParallelSolveEntityErrorError


class ParallelSolveEntityError(UniversalBaseModel):
    """
    Reported in a parallel-solve response slot when an individual rule or flow could not be executed. The reserved `$error` key cannot collide with a rule/flow's own output fields.
    """

    error: typing_extensions.Annotated[
        ParallelSolveEntityErrorError,
        FieldMetadata(alias="$error"),
        pydantic.Field(alias="$error", description="Details of the per-entity failure."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
