# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ParallelSolveRequestValue(UniversalBaseModel):
    rule: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="$rule")] = pydantic.Field(default=None)
    """
    Slug of the rule to execute
    """

    flow: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="$flow")] = pydantic.Field(default=None)
    """
    Slug of the flow to execute
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
