# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .rule_import_request_cell import RuleImportRequestCell
from .rule_import_response_cell import RuleImportResponseCell
from .rule_import_row_settings import RuleImportRowSettings


class RuleImportConditionRow(UniversalBaseModel):
    """
    A single rule row containing request conditions and response output.
    """

    request: typing.Dict[str, RuleImportRequestCell] = pydantic.Field()
    """
    Request-side cells keyed by request schema field key.
    """

    response: typing.Dict[str, RuleImportResponseCell] = pydantic.Field()
    """
    Response-side cells keyed by response schema field key.
    """

    settings: RuleImportRowSettings

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
