# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .rulebricks_flow_output_field_type import RulebricksFlowOutputFieldType


class RulebricksFlowOutputField(UniversalBaseModel):
    """
    A declared output of a dynamic node (code/api/db/soap/ai/for_each). Declaring outputs lets the expander render the output handle and keep generated connections.
    """

    key: str = pydantic.Field()
    """
    Output property key.
    """

    type: typing.Optional[RulebricksFlowOutputFieldType] = pydantic.Field(default=None)
    """
    Value type used for handle typing.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional display name.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
