# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class RulebricksFlowConnection(UniversalBaseModel):
    """
    A directed connection between two node refs. Data connections carry a property from `output` to `input`; control connections (`control: true`) gate the target on a Continue If.
    """

    from_: typing_extensions.Annotated[
        str, FieldMetadata(alias="from"), pydantic.Field(alias="from", description="Source node ref.")
    ]
    to: str = pydantic.Field()
    """
    Target node ref.
    """

    output: typing.Optional[str] = pydantic.Field(default=None)
    """
    (data) Source output key: a declared output of the source node, or - for a rule/origin source - one of the referenced rule's response field keys (an origin also exposes `request_<field>` passthroughs). Free-form; validated against the resolved rule at import time.
    """

    input: typing.Optional[str] = pydantic.Field(default=None)
    """
    (data) Target input key. Required for rule/entity targets, where it must be one of the referenced rule's request field keys. Free-form; validated against the resolved rule at import time.
    """

    control: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Set true for a Continue If gating edge (carries no data).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
