# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class RuleImportRowSettings(UniversalBaseModel):
    """
    Execution settings for a condition row.
    """

    enabled: bool = pydantic.Field()
    """
    Whether this row is active.
    """

    group_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="groupId"),
        pydantic.Field(alias="groupId", description="Optional group ID for grouped aggregation."),
    ] = None
    priority: float = pydantic.Field()
    """
    Row priority when multiple rows match.
    """

    schedule: typing.List[typing.Dict[str, typing.Any]] = pydantic.Field()
    """
    Optional schedule constraints for this row.
    """

    or_: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="or"),
        pydantic.Field(alias="or", description="When true, request cells in this row are evaluated with OR semantics."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
