# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .run_tests_response_failures_item_policy import RunTestsResponseFailuresItemPolicy


class RunTestsResponseFailuresItem(UniversalBaseModel):
    id: str
    name: str
    policy: RunTestsResponseFailuresItemPolicy
    critical: bool
    expected: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    The expected response for the test case.
    """

    actual: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    The response the rule/flow actually produced (null when the case failed to execute).
    """

    matched_rows: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    Rules only: the index(es) of the decision-table row(s) that fired for this case.
    """

    error_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    A human-readable evaluation error when the case failed to execute.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
