# This file was auto-generated by Fern from our API Definition.

import typing

SolveContextRuleRequest = typing.Dict[str, typing.Any]
"""
Optional request body for solving a rule against context. The entire body is merged with the instance state before rule evaluation.
"""
