# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cascade_result import CascadeResult
from .solve_context_rule_response_status import SolveContextRuleResponseStatus


class SolveContextRuleResponse(UniversalBaseModel):
    """
    Response after solving a rule against a context instance.
    """

    status: typing.Optional[SolveContextRuleResponseStatus] = pydantic.Field(default=None)
    """
    Whether the rule executed successfully.
    """

    context: typing.Optional[str] = pydantic.Field(default=None)
    """
    Combined identifier in format 'contextSlug:instanceId'.
    """

    rule: typing.Optional[str] = pydantic.Field(default=None)
    """
    The slug of the rule that was executed.
    """

    result: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The rule evaluation result (output values).
    """

    written_to_context: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of field keys that were written back to the context instance.
    """

    cascaded: typing.Optional[typing.List[CascadeResult]] = pydantic.Field(default=None)
    """
    Results from any cascaded evaluations triggered by the rule outputs.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
