# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cascade_result import CascadeResult
from .submit_context_data_response_status import SubmitContextDataResponseStatus


class SubmitContextDataResponse(UniversalBaseModel):
    """
    Response after submitting data, including any auto-executed evaluations.
    """

    context: typing.Optional[str] = pydantic.Field(default=None)
    """
    Combined identifier in format 'contextSlug:instanceId'.
    """

    state: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The merged state after submitting data and any auto-executed rules/flows.
    """

    status: typing.Optional[SubmitContextDataResponseStatus] = pydantic.Field(default=None)
    """
    Whether all required fields are present ('complete') or some are missing ('pending').
    """

    have: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of field keys that are currently populated.
    """

    need: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of required field keys that are still missing.
    """

    is_new: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this submission created a new instance (true) or updated an existing one (false).
    """

    expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the instance will expire based on context TTL.
    """

    cascaded: typing.Optional[typing.List[CascadeResult]] = pydantic.Field(default=None)
    """
    Results from auto-executed rules/flows and pending evaluation cascades.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
