# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .test_test_state import TestTestState


class Test(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for the test.
    """

    name: str = pydantic.Field()
    """
    The name of the test.
    """

    request: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    The request object for the test.
    """

    response: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    The expected response object for the test.
    """

    critical: bool = pydantic.Field()
    """
    Indicates whether the test is critical.
    """

    error: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates if the test resulted in an error. Null if test has not been executed.
    """

    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates if the test was successful. Null if test has not been executed.
    """

    test_state: typing.Optional[TestTestState] = pydantic.Field(default=None)
    """
    The state of the test after execution.
    """

    last_executed: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The timestamp when the test was last executed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
