# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .test_test_state_evaluation_error import TestTestStateEvaluationError


class TestTestState(UniversalBaseModel):
    """
    The state of the test after execution.
    """

    duration: typing.Optional[float] = pydantic.Field(default=None)
    """
    Execution time in seconds
    """

    response: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Actual response returned
    """

    conditions: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None
    http_status: typing.Optional[int] = pydantic.Field(default=None)
    """
    HTTP status code returned
    """

    success_idxs: typing.Optional[typing.List[int]] = None
    evaluation_error: typing.Optional[TestTestStateEvaluationError] = pydantic.Field(default=None)
    """
    Error message or flag indicating if evaluation error occurred
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
