# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpsertObjectRequestFieldRename(UniversalBaseModel):
    """
    Renames a field while preserving generated value IDs.
    """

    from_key: str = pydantic.Field()
    """
    Existing field key or schema path.
    """

    to_key: str = pydantic.Field()
    """
    New field key or schema path.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
