# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_invite_response_user import UserInviteResponseUser


class UserInviteResponse(UniversalBaseModel):
    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Success message indicating whether a new user was invited or an existing user's permissions were updated.
    """

    user: typing.Optional[UserInviteResponseUser] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
