# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UserGroup(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier of the user group.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the user group.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description of the user group.
    """

    members: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of member emails in the user group.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the user group was created.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
