# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UserInviteResponseUser(UniversalBaseModel):
    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email of the invited user.
    """

    role: typing.Optional[str] = pydantic.Field(default=None)
    """
    Role assigned to the user.
    """

    user_groups: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    User groups assigned to the user.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
