# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.context_relationships_response import ContextRelationshipsResponse
from ...types.create_relationship_response import CreateRelationshipResponse
from ...types.delete_relationship_response import DeleteRelationshipResponse
from .raw_client import AsyncRawRelationshipsClient, RawRelationshipsClient
from .types.create_relationship_request_relation_type import CreateRelationshipRequestRelationType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RelationshipsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRelationshipsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRelationshipsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRelationshipsClient
        """
        return self._raw_client

    def list(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ContextRelationshipsResponse:
        """
        List all relationships for a specific context.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContextRelationshipsResponse
            Success

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.contexts.relationships.list(
            id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        )
        """
        _response = self._raw_client.list(id, request_options=request_options)
        return _response.data

    def create(
        self,
        id: str,
        *,
        to_context_id: str,
        relation_type: CreateRelationshipRequestRelationType,
        foreign_key_fact: str,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateRelationshipResponse:
        """
        Create a new relationship between two contexts.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        to_context_id : str
            The ID of the target context.

        relation_type : CreateRelationshipRequestRelationType
            The type of relationship.

        foreign_key_fact : str
            The field key to use as the foreign key.

        name : typing.Optional[str]
            Display name for the relationship.

        description : typing.Optional[str]
            Description of the relationship.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateRelationshipResponse
            Relationship created successfully

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.contexts.relationships.create(
            id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            to_context_id="b2c3d4e5-f6a7-8901-bcde-f12345678901",
            relation_type="has_many",
            foreign_key_fact="customer_id",
            name="Customer Orders",
        )
        """
        _response = self._raw_client.create(
            id,
            to_context_id=to_context_id,
            relation_type=relation_type,
            foreign_key_fact=foreign_key_fact,
            name=name,
            description=description,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self, id: str, relationship: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteRelationshipResponse:
        """
        Delete a specific relationship between contexts.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        relationship : str
            The unique identifier for the relationship.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteRelationshipResponse
            Relationship deleted successfully

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.contexts.relationships.delete(
            id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            relationship="c3d4e5f6-a7b8-9012-cdef-123456789012",
        )
        """
        _response = self._raw_client.delete(id, relationship, request_options=request_options)
        return _response.data


class AsyncRelationshipsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRelationshipsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRelationshipsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRelationshipsClient
        """
        return self._raw_client

    async def list(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ContextRelationshipsResponse:
        """
        List all relationships for a specific context.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContextRelationshipsResponse
            Success

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.contexts.relationships.list(
                id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(id, request_options=request_options)
        return _response.data

    async def create(
        self,
        id: str,
        *,
        to_context_id: str,
        relation_type: CreateRelationshipRequestRelationType,
        foreign_key_fact: str,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateRelationshipResponse:
        """
        Create a new relationship between two contexts.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        to_context_id : str
            The ID of the target context.

        relation_type : CreateRelationshipRequestRelationType
            The type of relationship.

        foreign_key_fact : str
            The field key to use as the foreign key.

        name : typing.Optional[str]
            Display name for the relationship.

        description : typing.Optional[str]
            Description of the relationship.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateRelationshipResponse
            Relationship created successfully

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.contexts.relationships.create(
                id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                to_context_id="b2c3d4e5-f6a7-8901-bcde-f12345678901",
                relation_type="has_many",
                foreign_key_fact="customer_id",
                name="Customer Orders",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            id,
            to_context_id=to_context_id,
            relation_type=relation_type,
            foreign_key_fact=foreign_key_fact,
            name=name,
            description=description,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self, id: str, relationship: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteRelationshipResponse:
        """
        Delete a specific relationship between contexts.

        Parameters
        ----------
        id : str
            The unique identifier for the context.

        relationship : str
            The unique identifier for the relationship.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteRelationshipResponse
            Relationship deleted successfully

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.contexts.relationships.delete(
                id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                relationship="c3d4e5f6-a7b8-9012-cdef-123456789012",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, relationship, request_options=request_options)
        return _response.data
