# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.rule_export import RuleExport
from ...types.rule_list_response import RuleListResponse
from ...types.success_message import SuccessMessage
from .raw_client import AsyncRawRulesClient, RawRulesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RulesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRulesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRulesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRulesClient
        """
        return self._raw_client

    def delete(self, *, id: str, request_options: typing.Optional[RequestOptions] = None) -> SuccessMessage:
        """
        Delete a specific rule by its ID.

        Parameters
        ----------
        id : str
            The ID of the rule to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessMessage
            Rule deleted successfully

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.assets.rules.delete(
            id="2855f8da-2654-4df9-8903-8f797cbfe8eb",
        )
        """
        _response = self._raw_client.delete(id=id, request_options=request_options)
        return _response.data

    def pull(self, *, id: str, request_options: typing.Optional[RequestOptions] = None) -> RuleExport:
        """
        Export a specific rule by its ID.

        Parameters
        ----------
        id : str
            The ID of the rule to export.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RuleExport
            Successful response

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.assets.rules.pull(
            id="2855f8da-2654-4df9-8903-8f797cbfe8eb",
        )
        """
        _response = self._raw_client.pull(id=id, request_options=request_options)
        return _response.data

    def push(
        self, *, rule: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> RuleExport:
        """
        Import a rule into the user's account.

        Parameters
        ----------
        rule : typing.Dict[str, typing.Any]
            The rule data to import.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RuleExport
            Rule imported successfully

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.assets.rules.push(
            rule={"name": "Imported Rule", "description": "A rule imported via API"},
        )
        """
        _response = self._raw_client.push(rule=rule, request_options=request_options)
        return _response.data

    def list(
        self, *, folder: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> RuleListResponse:
        """
        List all rules in the organization. Optionally filter by folder name or ID.

        Parameters
        ----------
        folder : typing.Optional[str]
            Filter rules by folder name or folder ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RuleListResponse
            Success

        Examples
        --------
        from rulebricks import Rulebricks

        client = Rulebricks(
            api_key="YOUR_API_KEY",
        )
        client.assets.rules.list(
            folder="Marketing Rules",
        )
        """
        _response = self._raw_client.list(folder=folder, request_options=request_options)
        return _response.data


class AsyncRulesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRulesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRulesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRulesClient
        """
        return self._raw_client

    async def delete(self, *, id: str, request_options: typing.Optional[RequestOptions] = None) -> SuccessMessage:
        """
        Delete a specific rule by its ID.

        Parameters
        ----------
        id : str
            The ID of the rule to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessMessage
            Rule deleted successfully

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.assets.rules.delete(
                id="2855f8da-2654-4df9-8903-8f797cbfe8eb",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id=id, request_options=request_options)
        return _response.data

    async def pull(self, *, id: str, request_options: typing.Optional[RequestOptions] = None) -> RuleExport:
        """
        Export a specific rule by its ID.

        Parameters
        ----------
        id : str
            The ID of the rule to export.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RuleExport
            Successful response

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.assets.rules.pull(
                id="2855f8da-2654-4df9-8903-8f797cbfe8eb",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.pull(id=id, request_options=request_options)
        return _response.data

    async def push(
        self, *, rule: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> RuleExport:
        """
        Import a rule into the user's account.

        Parameters
        ----------
        rule : typing.Dict[str, typing.Any]
            The rule data to import.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RuleExport
            Rule imported successfully

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.assets.rules.push(
                rule={
                    "name": "Imported Rule",
                    "description": "A rule imported via API",
                },
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.push(rule=rule, request_options=request_options)
        return _response.data

    async def list(
        self, *, folder: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> RuleListResponse:
        """
        List all rules in the organization. Optionally filter by folder name or ID.

        Parameters
        ----------
        folder : typing.Optional[str]
            Filter rules by folder name or folder ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RuleListResponse
            Success

        Examples
        --------
        import asyncio

        from rulebricks import AsyncRulebricks

        client = AsyncRulebricks(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.assets.rules.list(
                folder="Marketing Rules",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(folder=folder, request_options=request_options)
        return _response.data
